### ISSUE TITLE
Postgres 9.6 default role pg_signal_backend

### ISSUE THREAD

**Issue by AgilDat** [larskanis/pg-ldap-sync#12]
Problem when sync with postgres 9.6 because `role pg_signal_backend` is created by default in postgres: 

trace
```
I, [2017-01-26T11:38:45.007290 #32350]  INFO -- : group stat: create: 0 drop: 1 keep: 0
I, [2017-01-26T11:38:45.007350 #32350]  INFO -- : membership stat: grant: 0 revoke: 0 keep: 0
I, [2017-01-26T11:38:45.007414 #32350]  INFO -- : SQL: DROP ROLE "pg_signal_backend"
/root/.gem/ruby/gems/postgres-pr-0.7.0/lib/postgres-pr/connection.rb:145:in `query': ERROR	VERROR	C2BP01	Mcannot drop role pg_signal_backend because it is required by the database system	Fpg_shdepend.c	L577	RcheckSharedDependencies (DatabaseError)
	from /root/.gem/ruby/gems/postgres-pr-0.7.0/lib/postgres-pr/postgres-compat.rb:38:in `query'
	from /root/.gem/ruby/gems/pg-ldap-sync-0.1.1/lib/pg_ldap_sync/application.rb:217:in `pg_exec_modify'
	from /root/.gem/ruby/gems/pg-ldap-sync-0.1.1/lib/pg_ldap_sync/application.rb:232:in `drop_pg_role'
	from /root/.gem/ruby/gems/pg-ldap-sync-0.1.1/lib/pg_ldap_sync/application.rb:238:in `block in sync_roles_to_pg'
	from /root/.gem/ruby/gems/pg-ldap-sync-0.1.1/lib/pg_ldap_sync/application.rb:236:in `each'
	from /root/.gem/ruby/gems/pg-ldap-sync-0.1.1/lib/pg_ldap_sync/application.rb:236:in `sync_roles_to_pg'
	from /root/.gem/ruby/gems/pg-ldap-sync-0.1.1/lib/pg_ldap_sync/application.rb:330:in `start!'
	from /root/.gem/ruby/gems/pg-ldap-sync-0.1.1/lib/pg_ldap_sync/application.rb:353:in `run'
	from /root/.gem/ruby/gems/pg-ldap-sync-0.1.1/bin/pg_ldap_sync:6:in `<main>'

```

**Comment by AgilDat** [comment]
Working with this configuration:
```
pg_groups:
  # Filter for identifying LDAP generated groups in the database.
  # It's the WHERE-condition to "SELECT rolname, oid FROM pg_roles"
  filter: oid IN (SELECT pam.member FROM pg_auth_members pam JOIN pg_roles pr ON pr.oid=pam.roleid WHERE pr.rolname='ldap_groups')
 # Options for CREATE RULE statements
  create_options: NOLOGIN
  grant_options:
```
