### ISSUE TITLE
Only synchronize users for specific groups

### ISSUE THREAD

**Issue by lampi87** [larskanis/pg-ldap-sync#27]
Hi,

unfortunately I wasn't able to configure yaml properly.
I just want to synchronize users, which are assigned to given groups, nevertheless of the users's OU. Is this possible?
Are the permissions granted to users or groups on postgres side? Different ldap groups need different DB rights.

Best regards

**Comment by larskanis** [comment]
> I just want to synchronize users, which are assigned to given groups, nevertheless of the users's OU. Is this possible?

Have a look at [config2.yaml](https://github.com/larskanis/pg-ldap-sync/blob/master/config/sample-config2.yaml). You can use all kinds of filters of the LDAP query language. It's best to use a LDAP browser to try out, which query fits your needs.

I'm not particular fit with LDAP, so that I don't know from memory, whether and how group membership can be used to select users. Usually I select the users based on some user attributes like:
```
ldap_users:
  base: OU=comcard,OU=comcard,DC=comcard-nt,DC=de
  filter: (|(&(objectClass=person)(objectClass=organizationalPerson)(givenName=*)(sn=*))(cn=Instandhaltung)(cn=giftcard)(cn=rudy))
  name_attribute: sAMAccountName
```
This takes all users with a `givenName` and a `sn` attribute and adds some particular manually selected users.

> Are the permissions granted to users or groups on postgres side? Different ldap groups need different DB rights.

That's the intension of the tool. All memberships of selected LDAP users and groups are applied to PostgreSQL. You can then grant your synchronized PostgreSQL roles the required permissions on tables, etc. However keep in mind, that only the groups that are selected by the `filter:` attribute are considered for synchronization.
