### ISSUE TITLE
'wrong number of arguments' with postgres-pr

### ISSUE THREAD

**Issue by larskanis** [larskanis/pg-ldap-sync#3]
I’m trying to use pg_ldap_sync and am getting an error. I’ve started with a brand new ubuntu 14.04 server. I setup a postgres server and did the following:

```
sudo apt-get install ruby rubygems-integration
sudo gem install pg-ldap-sync postgres-pr
```

Here’s my config file:

```
# With this sample config the distinction between PG groups and users is
# done by the LOGIN/NOLOGIN attribute. Any non-superuser account
# is considered as LDAP-synchronized.

# Connection parameters to LDAP server
# see also: http://net-ldap.rubyforge.org/Net/LDAP.html#method-c-new
ldap_connection:
  host: ds1.aws.gnshc.com
  port: 1636
  auth:
    method: :simple
    username: uid=service_postgres,ou=ServiceAccounts,dc=ops,dc=gnshc,dc=com
    password: test
  encryption: 
    method: :simple_tls

# Search parameters for LDAP users which should be synchronized
ldap_users:
  base: ou=People,ou=gns,dc=tenants,dc=gnshc,dc=com
  # LDAP filter (according to RFC 2254)
  # defines to users in LDAP to be synchronized
  filter: (&(objectClass=inetOrgPerson)(isMemberOf=cn=authorized_users,ou=nonep-database,ou=Postgres,ou=Applications,dc=ops,dc=gnshc,dc=com))
  # this attribute is used as PG role name
  name_attribute: uid

# Search parameters for LDAP groups which should be synchronized
ldap_groups:
  base: ou=nonep-database,ou=Postgres,ou=Applications,dc=ops,dc=gnshc,dc=com
  filter: (&(objectClass=groupOfUniqueNames)(ou=pg_role))
  # this attribute is used as PG role name
  name_attribute: cn
  # this attribute must reference to all member DN's of the given group
  member_attribute: uniqueMember

# Connection parameters to PostgreSQL server
# see also: http://rubydoc.info/gems/pg/PG/Connection#initialize-instance_method
pg_connection:
  host: localhost
  dbname: postgres
  user: postgres
  password: test

pg_users:
  # Filter for identifying LDAP generated users in the database.
  # It's the WHERE-condition to "SELECT rolname, oid FROM pg_roles"
  filter: oid IN (SELECT pam.member FROM pg_auth_members pam JOIN pg_roles pr ON pr.oid=pam.roleid WHERE pr.rolname='authorized_users')
  # Options for CREATE RULE statements
  create_options: LOGIN IN ROLE ldap_users

pg_groups:
  # Filter for identifying LDAP generated groups in the database.
  # It's the WHERE-condition to "SELECT rolname, oid FROM pg_roles"
  filter: oid IN (SELECT pam.member FROM pg_auth_members pam JOIN pg_roles pr ON pr.oid=pam.roleid WHERE pr.rolname='authorized_users')
  # Options for CREATE RULE statements
  create_options: NOLOGIN IN ROLE ldap_groups
  grant_options:
```

Then I try test and get the following:

```
postgres@openam2:~$ pg_ldap_sync -c ~/pgsync.yml -vv -t
I, [2015-10-06T14:55:59.901793 #13348]  INFO -- : found user-dn: uid=csanchez,ou=People,ou=gns,dc=tenants,dc=gnshc,dc=com
I, [2015-10-06T14:55:59.942828 #13348]  INFO -- : found group-dn: cn=authorized_users,ou=nonep-database,ou=Postgres,ou=Applications,dc=ops,dc=gnshc,dc=com
I, [2015-10-06T14:55:59.943334 #13348]  INFO -- : found group-dn: cn=marketscan,ou=nonep-database,ou=Postgres,ou=Applications,dc=ops,dc=gnshc,dc=com
I, [2015-10-06T14:55:59.943731 #13348]  INFO -- : found group-dn: cn=developers,ou=nonep-database,ou=Postgres,ou=Applications,dc=ops,dc=gnshc,dc=com
/var/lib/gems/1.9.1/gems/postgres-pr-0.7.0/lib/postgres-pr/postgres-compat.rb:16:in `initialize': wrong number of arguments (1 for 7) (ArgumentError)
        from /var/lib/gems/1.9.1/gems/pg-ldap-sync-0.1.1/lib/pg_ldap_sync/application.rb:317:in `new'
        from /var/lib/gems/1.9.1/gems/pg-ldap-sync-0.1.1/lib/pg_ldap_sync/application.rb:317:in `start!'
        from /var/lib/gems/1.9.1/gems/pg-ldap-sync-0.1.1/lib/pg_ldap_sync/application.rb:353:in `run'
        from /var/lib/gems/1.9.1/gems/pg-ldap-sync-0.1.1/bin/pg_ldap_sync:6:in `<top (required)>'
        from /usr/local/bin/pg_ldap_sync:23:in `load'
        from /usr/local/bin/pg_ldap_sync:23:in `<main>’
```
