### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by stijacicreveal** [larskanis/pg-ldap-sync#30]
Hello,

This is my first time to try to use pg-ldap-sync and before I try it on production environment I first installed it on my Windows 10 pro laptop and I encounter an issue. After calling a command pg_ldap_sync -c config.yaml -vv or pg_ldap_sync -c config.yaml -vv -t I am getting following:

Traceback (most recent call last):
        5: from C:/Ruby27-x64/bin/pg_ldap_sync:23:in `<main>'
        4: from C:/Ruby27-x64/bin/pg_ldap_sync:23:in `load'
        3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/pg-ldap-sync-0.2.0/exe/pg_ldap_sync:6:in `<top (required)>'
        2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/pg-ldap-sync-0.2.0/lib/pg_ldap_sync/application.rb:355:in `run'
        1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/pg-ldap-sync-0.2.0/lib/pg_ldap_sync/application.rb:305:in `start!'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/pg-ldap-sync-0.2.0/lib/pg_ldap_sync/application.rb:76:in `search_ldap_users': LDAP: Invalid Credentials (PgLdapSync::LdapError)

LDAP ports are open on domain controller and on my PC, I am using domain administrator in config.yaml, also I tried different Ruby versions... and really not sure how to troubleshoot more. 
Can someone point me where can be an issue here? 

Thanks in advance!

Regards,
Nikola

**Comment by larskanis** [comment]
I think the error message is pretty precise: `LDAP: Invalid Credentials (PgLdapSync::LdapError)`. So I would say that either the username or the password isn't correct.

I use the following parameters for an AD connection successfully:

```yaml
ldap_connection:
  host: COMDC2.comcard.de
  port: 636
  encryption:
    method: :simple_tls
  auth:
    method: :simple
    username: CN=_ldap,OU=!Serviceaccounts,OU=comcard,DC=comcard,DC=de
    password: my_secret_pw
```
Maybe you shouldn't use a domain administrator but an unprivileged user instead.
