### ISSUE TITLE
[Feature request] Add support for setting values from env

### ISSUE THREAD

**Issue by heckad** [larskanis/pg-ldap-sync#31]
Config example 
```
ldap_connection:
  host: $LDAP_SERVER
  port: 389
  auth:
    method: :simple
    username: CN=admin,OU=Admin,OU=Domain Services,dc=admin,dc=com
    password: $LDAP_SERVER_ADMIN_PASSWORD
```
